# file: /Users/tim/code/pyv/mono/pyvider/src/pyvider/exceptions/__init__.py
# hypothesis_version: 6.137.1

['CapabilityError', 'ConversionError', 'DataSourceError', 'DeserializationError', 'FunctionError', 'GRPCConnectionError', 'GRPCError', 'InvalidTypeError', 'NetworkError', 'PluginError', 'ProviderError', 'PyviderError', 'PyviderValueError', 'RateLimitError', 'ResourceError', 'SchemaError', 'SchemaParseError', 'SerializationError', 'UnsupportedTypeError', 'ValidationError', 'WireFormatError']